[chain]
net_type="aptos"
main_rpc_endpoint="https://fullnode.mainnet.aptoslabs.com/v1"
test_rpc_endpoint="https://fullnode.testnet.aptoslabs.com/v1"
dev_rpc_endpoint="https://fullnode.devnet.aptoslabs.com/v1"

